# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-10 21:24
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_f_name', models.CharField(max_length=15, verbose_name='First Name')),
                ('p_l_name', models.CharField(max_length=15, verbose_name='Last Name')),
                ('billing_address', models.CharField(max_length=50, verbose_name='Billing Address')),
                ('email', models.EmailField(default=0, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=10, verbose_name='Type of payment')),
            ],
        ),
        migrations.CreateModel(
            name='SeatsFree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sf_date', models.DateTimeField(help_text='All reservations start June 1st 2017, 6:00am', verbose_name='Date')),
                ('sf_count', models.PositiveIntegerField(help_text='0 <= n <= 448', validators=[django.core.validators.MaxValueValidator(448)], verbose_name='Free Seats in Segment')),
            ],
        ),
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seg_fare', models.IntegerField(verbose_name='Fare')),
                ('seg_distance', models.IntegerField(default=0, verbose_name='Mileage Between Stations')),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_name', models.CharField(max_length=50, unique=True, verbose_name='Station Name')),
                ('station_symbol', models.CharField(max_length=5, unique=True, verbose_name='Station Symbol')),
            ],
        ),
        migrations.CreateModel(
            name='StopsAt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sa_time_in', models.TimeField(verbose_name='Time-In of Train at Station')),
                ('sa_time_out', models.TimeField(blank=True, null=True, verbose_name='Time-out of train at Station')),
                ('sa_station', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='station+', to='main.Station', verbose_name='Station Where Train Stops')),
            ],
        ),
        migrations.CreateModel(
            name='TicketTrip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_fare', models.IntegerField(default=0, verbose_name='Fare')),
                ('trip_date', models.DateTimeField(verbose_name='Trip Date')),
                ('trip_end_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='t_end+', to='main.Station', verbose_name='Trip End Station')),
                ('trip_pay_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='t_pay', to='main.PaymentMethod', verbose_name='Choose Payment')),
                ('trip_segment_end', models.ForeignKey(blank=True, help_text='Shows only north-end station of segment', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='s_end+', to='main.Segment', verbose_name='Segment End')),
                ('trip_segment_start', models.ForeignKey(blank=True, help_text='Shows only north-end station of segment', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='s_start+', to='main.Segment', verbose_name='Segment Start')),
                ('trip_start_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='t_start+', to='main.Station', verbose_name='Trip Start Station')),
            ],
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_number', models.CharField(max_length=15, verbose_name='Train Number')),
                ('train_direction', models.BooleanField(help_text='North = 1, South = 0', verbose_name='Direction')),
                ('train_days', models.CharField(help_text='M-T-W-Th-F-S-Su', max_length=20, verbose_name='Days train runs')),
                ('end_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='s_end', to='main.Station', verbose_name='End Station')),
                ('start_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='s_start', to='main.Station', verbose_name='Start Station')),
            ],
        ),
        migrations.AddField(
            model_name='tickettrip',
            name='trip_train',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Train', verbose_name='Train'),
        ),
        migrations.AddField(
            model_name='stopsat',
            name='sa_train',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='train+', to='main.Train', verbose_name='Which Train?'),
        ),
        migrations.AddField(
            model_name='segment',
            name='seg_north_end',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='n_end+', to='main.Station', verbose_name='Segment North End'),
        ),
        migrations.AddField(
            model_name='segment',
            name='seg_south_end',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='s_end+', to='main.Station', verbose_name='Segment South End'),
        ),
        migrations.AddField(
            model_name='seatsfree',
            name='sf_segment',
            field=models.ForeignKey(help_text='Shows only north-end station of segment', on_delete=django.db.models.deletion.CASCADE, related_name='seg+', to='main.Segment', verbose_name='Segment'),
        ),
        migrations.AddField(
            model_name='seatsfree',
            name='sf_train',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sf_train+', to='main.Train', verbose_name='Train in Segment'),
        ),
    ]
